### PR TITLE
OSX installation instructions

### PR DESCRIPTION
**Pull request by jalevine**
I've written up some of the instructions for compiling on OSX Sierra 10.12.5

Note that these were tested with ParaView 5.4.0 (and thus require the patch for that), but they are otherwise identical to ParaView 5.3.0.

### CODE REVIEW

**Comment by julien-tierny** [comment]
Hi Josh,
thanks a lot for these instructions.
I was wondering: for all these sections that are identical (with the text "These instructions are identical."), would it be better to add a link pointing to the matching section in the main installation page or to copy-paste the text from the main installation page (to make the osx installation page self contained)?

what do you think?
cheers,

**Comment by jalevine** [comment]
I agree this should be done better.  It ultimately depends on the use case.  The way the site map is set up, right now one has to go through the default instructions.html to find the osx instructions.  As you can see, I created these instructions by following the unix ones step-by-step.  I kept things organized in this way, for now, so that we could also refer back to "what was different" about OSX.

I see a couple of options:
(1) Change installation.html to be a jump point to various installation pages (e.g. installation-linux.html, installation-osx.html, maybe installation-windows.html).  Perhaps these could also track instructions specific to various versions of TTK/ParaView (e.g. installation-osx-ttk0.9.1-paraview5.4.0.html).  In that case, it makes sense to duplicate information as opposed to adding links to point to matching sections, since it might be that the instructions have no shared information at all.

(2) Create a single master installation page that shows where the instructions differ in a side-by-side manner.  This would potentially look something like https://www.paraview.org/Wiki/ParaView:Build_And_Install
(where the pink/blue boxes help differentiate based on platform).  

My personal preference is probably for (1), even though it could lead to a situation where redundant information is duplicated.  But, I don't feel strongly either way.  What do you think?

**Comment by julien-tierny** [comment]
option 1 can be put together quickly.
option 2 is probably better in the long run for maintenance purpose.
it's up to you. 
I'm ok with option 1 (let's consider option 2 when we have clean Windows instructions, kind poke @harishd10).

also, could you:
- provide exact command lines for section 2 (if it is possible / making sense)
- update 0.9.1 to 0.9.2 (I bumped the version to match paraview)

thanks :)

**Comment by jalevine** [comment]
I've updated accordingly -- added instructions for sections 1, 3, and 4 as well as the command line for section 2.  Versions are also updated for 0.9.2/5.4.0.

**Comment by julien-tierny** [comment]
Great stuff.
Thanks!

**Pull request merged**
