### PR TITLE
Small edit for optional dependencies and library updates

### PR DESCRIPTION
**Pull request by jalevine**
(1) Tested compilation with zlib and sqlite3
(2) Updated the versions of some of the dependencies to current versions in homebrew

### CODE REVIEW

**Comment by jalevine** [comment]
Oh i also have graphviz added, found by cmake, and compiled.

**Comment by julien-tierny** [comment]
awesome, thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
btw, to test these optional dependencies at runtime, you can use the following states from ttk-data:

- graphviz: states/nestedTrackingGraph.pvsm 
https://topology-tool-kit.github.io/img/gallery/nestedTrackingGraph.jpg

- scikit-learn: states/1manifoldLearning .pvsm
https://topology-tool-kit.github.io/img/gallery/1manifoldLearning.jpeg

- sqlite3: states/trackingFromOverlap.pvsm

- zlib/zfp: there's no state yet for this one but you can take whatever scalar field defined on a regular grid and do "File" / "Save data..." and use the ".ttk" extension (for TopologyToolKit Compressed Image Data). it will use zlib by default and also zfp if you set the zfp bit budget higher than 0.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by jalevine** [comment]
graphviz and sqlite3 are tested and appear to work. 

sklearn is more complex (still testing issues out of band)

zfp I don't have up, but topological compression did appear to work with zlib

**Pull request merged**
