### PR TITLE
Updates for TTK Tutorial at IEEE VIS 2019

### PR DESCRIPTION
**Pull request by jalevine**

### CODE REVIEW

**Comment by jalevine** [comment]
I've also added compilation instructions for Mojave.

**Comment by julien-tierny** [comment]
hi josh,

thanks a lot!

is the commit from the PR #230 required for these instructions to work smoothly? 

(if so, we may need to delay their merge until the 0.9.8 release).

thanks for your feedback,
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by jalevine** [comment]
Nope!  I tested with both 0.9.7 release and things compile this way.  The other PR is to make the head build on MacOS

**Comment by julien-tierny** [comment]
gotcha, thanks.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by jalevine** [comment]
Just pinging/reminding on this PR.

**Comment by julien-tierny** [comment]
alright, looks good.
in the future, in that kind of situation, thanks for doing separate PRs (one for the tutorial update and one for the installation updates).
cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Pull request merged**
